version: '3.8'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    expose:
      - "80"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    environment:
      - DOMAIN=example.com # replace with your domain
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
